# Generated by Django 5.2.7 on 2025-11-03 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='payment_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending Payment'),
                    ('completed', 'Payment Completed')
                ],
                default='pending',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='bid',
            name='quantity',
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)]
            ),
            preserve_default=False,
        ),
    ]
