# Generated by Django 5.2.7 on 2025-10-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='bid_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
