# Generated by Django 5.2.7 on 2025-10-30 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivationbooking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='adminpanel.cultivationslot'),
        ),
    ]
