# Generated by Django 5.2.7 on 2025-11-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_bid_payment_status_bid_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
