# Generated by Django 5.2.7 on 2025-10-31 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_productlisting_bid_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='bid_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
