# Generated by Django 5.2.7 on 2025-11-03 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_productlisting_reserved_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='reserved_quantity',
        ),
    ]
