# Generated by Django 5.2.7 on 2025-11-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_productlisting_lat_productlisting_long_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='long',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='maps_location',
        ),
    ]
