# Generated by Django 5.2.7 on 2025-11-03 04:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_users', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_bookings', models.IntegerField(default=0)),
                ('total_listings', models.IntegerField(default=0)),
                ('farmer_count', models.IntegerField(default=0)),
                ('buyer_count', models.IntegerField(default=0)),
                ('storage_bookings', models.IntegerField(default=0)),
                ('cultivation_bookings', models.IntegerField(default=0)),
                ('active_listings', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Analytics Data',
                'ordering': ['-date'],
            },
        ),
    ]
