# Generated by Django 5.2.7 on 2025-11-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='data_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('overview', 'Overall Summary'), ('bookings', 'Cultivation & Storage Bookings'), ('revenue', 'Total Revenue'), ('market', 'Marketplace Performance'), ('users', 'User Statistics')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
