# Generated by Django 5.2.7 on 2025-11-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_cultivationslot_lat_cultivationslot_long_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivationslot',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='cultivationslot',
            name='long',
        ),
        migrations.RemoveField(
            model_name='cultivationslot',
            name='maps_location',
        ),
        migrations.RemoveField(
            model_name='landrecord',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='landrecord',
            name='long',
        ),
        migrations.RemoveField(
            model_name='landrecord',
            name='maps_location',
        ),
        migrations.RemoveField(
            model_name='storageslot',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='storageslot',
            name='long',
        ),
        migrations.RemoveField(
            model_name='storageslot',
            name='maps_location',
        ),
    ]
