# Generated by Django 5.2.7 on 2025-11-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_lat_customuser_long_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='long',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='maps_location',
        ),
    ]
