# Generated by Django 5.2.7 on 2025-11-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_completed', 'Payment Completed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending_payment', max_length=20),
        ),
    ]
