# Generated by Django 5.2.7 on 2025-11-03 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_purchase_payment_completed_alter_purchase_status'),
        ('farmer', '0003_productlisting_reserved_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmer.bid'),
        ),
    ]
